### ISSUE TITLE
Signup for Vipps Invoicing not valid for all systems

### ISSUE THREAD

**Issue by steffanhalv** [vippsas/vipps-invoice-api#1]
I tried to register for the tripletex system at https://vippsbedrift.no/signup/vippsfaktura/, but only the systems below is valid in selection dropdown box at signup:

![skjermbilde 2018-08-16 kl 13 34 06](https://user-images.githubusercontent.com/4593184/44206138-1c137a80-a159-11e8-9306-3499eb7a2df0.png)

I selected 24sevenoffice at signup, as the integration keys hopefully is identical for all systems.
It should be an option called 'Custom integration' for those who use other invoicing systems other than 'Official supported' systems, as invoiceing services may vary.

Dropdown im refering to, which should have a 'Custom' option:
![skjermbilde 2018-08-16 kl 13 41 45](https://user-images.githubusercontent.com/4593184/44206461-26824400-a15a-11e8-8dd9-111f73dad4bf.png)

**Comment by cloveras** [comment]
Hi, @steffanhalv 

The screenshots seem to be for the existing, soon-to-be-phased-out "Vipps Faktura". We are aware of the confusing naming, and apologise for making this a bit tricky. 

The dropdown lists the systems that have Vipps integration. 

Are you working on a Tripletex integration? For access to the test environment, and API keys, please send an email to integration@vipps.no.

Also: Please see the dates listed on https://github.com/vippsas/vipps-invoice-api

Christian, Vipps

**Comment by steffanhalv** [comment]
@cloveras Thanks, I will take contact 👍
