### ISSUE TITLE
Does invoices have a predefined lifetime?

### ISSUE THREAD

**Issue by aaberg** [vippsas/vipps-invoice-api#19]
Hi,

How long time can we expect to be able to get information about an invoice through the API? Will an invoice get deleted after a predefined period?

Regards
Lars Aaberg

**Comment by aaberg** [comment]
In case it wasn't clear in the original description, this question is meant for historic payments. 

Will we for instance be able to fetch information about an invoice with the `/invoices/{invoiceId}` endpoint two years after the invoice is approved? And how long after a payment is processed, will the urls from the `/invoices/{invoiceId}/commercialInvoice` and `/invoices/{invoiceId}/attachments/{attachmentId}` work?

**Comment by frohal** [comment]
@aaberg I can answer for the latter two:
Those urls will work as long as the invoice-hotel servicen them still accepts the urls' and have the documents in the archive. This means - ofc - that this will vay depending on the issuers agreement with the invoice-hotels.  Some has 18 months , sm have 10 years...

**Comment by cloveras** [comment]
Thanks, @frohal! I have added a snippet at the end of https://github.com/vippsas/vipps-invoice-api/blob/master/vipps-invoice-api.md#typical-flow

**Comment by aaberg** [comment]
That answers my question. Thanks!
