### ISSUE TITLE
Push notifications 

### ISSUE THREAD

**Issue by aaberg** [vippsas/vipps-invoice-api#3]
Hi,

I'm working with online and mobile banking at Sparebanken Vest. We are still in the early phase of planning and developing our integration with VIPPS invoices.

We would like to know, if you plan to make it possible for us to send push notifications from our app to our customers, when they receive a VIPPS invoice? 

Regards
Lars Aaberg

**Comment by cloveras** [comment]
Hi @aaberg 

We are working on making it possible to send push alerts for Vipps Regninger in multiple channels (Vipps, Sparebanken Vest, etc), and let the user decide which alerts to receive. 

So: Yes 🎉

Please note that Vipps Regninger is being developed, and that this is based on what we know _now_, an that this may change.

Christian, Vipps

**Comment by aaberg** [comment]
Hi @cloveras, thanks for your quick answer.

Will we receive a notification when this gets available for us to try out?

**Comment by aaberg** [comment]
👍
