### ISSUE TITLE
Authentication with APIM (Azure API Manager)

### ISSUE THREAD

**Issue by cloveras** [vippsas/vipps-invoice-api#6]
The work with APIM is taking longer than planned, and we will not have APIM authentication today.

We will update this issue with more information.

**Comment by erikaxel** [comment]
Hi,

Do you have any updates on the deadlines?

**Comment by cloveras** [comment]
Update: We have set up APIM for internal testing and verfification, and will make it available shortly. Please note that test data created in the current environment will have to be re-created once APIM is activated.

**Comment by cloveras** [comment]
APIM authentication is now available, in parallel with the old solution. Please contact us at integration@vipps.no to get credentials, etc.

**Comment by cloveras** [comment]
And: New Swagger files with APIM authentication added:
Invoice Service Provider (ISP): https://vippsas.github.io/vipps-invoice-api/isp.html
Invoice Payment Provider (IPP): https://vippsas.github.io/vipps-invoice-api/ipp.html
Please let us know if there are any issues with the new files, and we will fix it ASAP.
