### ISSUE TITLE
typo in endpoint

### ISSUE THREAD

**Issue by ahysing** [vippsas/vipps-invoice-api#87]
"The recipientToken is obtained by calling POST://recipients/tokens. This recipientToken can then be used in the request body to PUT:/invoices/{invoiceId} to the specified recipient."
should probably be
"The recipientToken is obtained by calling POST:/recipients/tokens. This recipientToken can then be used in the request body to PUT:/invoices/{invoiceId} to the specified recipient." Note the single slash after POST

**Comment by flinkgutt** [comment]
Fixed.
Don't honestly know how this could have been ignored for so long. Sorry about this.
